#!/usr/bin/python
#coding: UTF-8
###############################################################################
# @(#) Price Checker for Amazon.co.jp
#
# Get a price from Amazon.co.jp
#
# Copyright (c) 2013 Tats Shibata
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
###############################################################################
# {{{ const

__version__ = "1.0.0"

BASE_URL = "http://www.amazon.co.jp/dp/"
USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11"

#}}}
# {{{ import

import getopt
import re
import sys
import urllib
import urllib2

# }}}
# {{{ usage()

def usage():
  print >>sys.stderr, """
[USAGE] amazon-price-checker [-V] <ASIN>

OPTION:
  -V, --version     Output version information and exit

RETURN CODE:
  0                 Success
  1                 Error but you can fix yourself
  2                 Critical Error
 -1                 Unexpected Error. File a bug
"""

# }}}
# {{{ version()

def version():
  print """Price Checker for Amazon.co.jp %s
""" % (__version__)

# }}}
# {{{ Option

class Option(object):
  def __init__(self, opts, args):
    self._set_opts(opts)
    self._set_args(args)

  def _set_opts(self, opts):
    for o, a in opts:
      if o in ("-V", "--version"):
        version()
        sys.exit(1)

  def _set_args(self, args):
    try:
      self.asin = args[0]
    except IndexError:
      print >>sys.stderr, "[ERROR] ASIN is required"
      usage()
      sys.exit(1)

# }}}
# {{{ valid_opt()

def valid_opt(argv):
  try:
    opts, args = getopt.gnu_getopt(
      argv[1:],
      "V",
      ["version"]
    )
  except getopt.GetoptError:
    print >>sys.stderr, "[ERROR] Unknown option"
    usage()
    sys.exit(1)

  return Option(opts, args)

# }}}
# {{{ buid_opener()

def buid_opener():
  opener = urllib2.build_opener()
  opener.addheaders = [('User-Agent', USER_AGENT)]

  return opener

# }}}
# {{{ req_product()

def req_product(opener, asin):
  try:
    res = opener.open(BASE_URL + asin)
  except urllib2.URLError:
    print >>sys.stderr, "[ERROR] URL request error [URL=%s]" % (BASE_URL + asin)
    sys.exit(1)

  return res.read().decode("shift_jis", "replace")

# }}}
# {{{ get_price()

def get_price(res):
  pat = re.compile(r'<span id="actualPriceValue">.+ ([0-9,]+)')
  price = "-----"

  for match in pat.finditer(res):
    price = match.group(1).replace(",", "")

  return price

# }}}
# {{{ main()

def main():
  opt = valid_opt(sys.argv)

  opener = buid_opener()

  res = req_product(opener, opt.asin)
  print get_price(res)

if __name__ == "__main__":
  main()
